name: Build

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependency
        run: |
          sudo apt update
          sudo apt install -y python3

      - name: Run python build script
        run: python3 build.py

      - name: Create archive
        uses: action/upload-artifacts
        with:
            name: Upload tar.xz
            path: gfaerny.tar.xz          
